# EasyNiddleNavigation ProGuard Rules

# 1. Preserve all classes and members of the library
-keep class dev.ishant.easyniddle.** { *; }
-keepclassmembers class dev.ishant.easyniddle.** { *; }

# 2. Keep all implementations of SerializableRoute
# This is critical because routes are serialized and deserialized by name/type.
-keep interface dev.ishant.easyniddle.navigation.SerializableRoute { *; }
-keep class * implements dev.ishant.easyniddle.navigation.SerializableRoute { *; }

# 3. Kotlin Serialization specific rules
# Since the library relies on Kotlin Serialization for state saving in Nav 3
-keepattributes *Annotation*, EnclosingMethod, InnerClasses, Signature

# Keep serializable classes and their companion objects
-keep @kotlinx.serialization.Serializable class * {
    *** Companion;
}

# Keep the serializer methods generated by the compiler plugin
-keepclassmembers class * {
    *** Companion;
}

-keepclassmembers class * {
    @kotlinx.serialization.Serializer *;
}

# 4. Preserve NavKey (base of Navigation 3)
-keep interface androidx.navigation3.runtime.NavKey { *; }

# 5. General debugging support (Optional but recommended)
-keepattributes SourceFile, LineNumberTable
-renamesourcefileattribute SourceFile
